#!/usr/bin/env python

import os
import sys


def builtin_echo(args):
    print(" ".join(args))


def builtin_exit(args):
    exit()


BUILTIN_COMMAND_FUNC_MAPPING = {
    "echo": builtin_echo,
    "exit": builtin_exit,
}


def find_command(command):
    for path in os.environ["PATH"].split(":"):
        path = os.path.join(path, command)
        if os.path.exists(path) and not os.path.isdir(path):
            return path
    return None


def main():
    while True:
        line = input("> ")
        tokens = line.split()

        if len(tokens) == 0:
            continue

        command = tokens[0]
        args = tokens[1:]

        if command in BUILTIN_COMMAND_FUNC_MAPPING:
            func = BUILTIN_COMMAND_FUNC_MAPPING[command]
            func(args)
        else:
            command_path = find_command(command)

            if command_path is None:
                print(f"{command}: command not found", file=sys.stderr)

            pid = os.fork()

            if pid < 0:
                print("fork failed", file=sys.stderr)
            elif pid == 0:
                os.execve(command_path, [command_path] + args, os.environ)
            else:
                os.waitpid(pid, 0)


if __name__ == "__main__":
    main()
